modLoader="javafml"
loaderVersion="[36,)"
license="Copyright © 2021 - 2022 Erinium - All Rights Reserved."

[[mods]]
modId="erinium"
version="1.0.3"
displayName="Erinium"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://discord.gg/26DzRJCTQs"
authors="killi, MCreator"
description='''
Mod crée par JLSkyzer
'''

[[dependencies.erinium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




