
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package fr.erinagroups.erinium.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.RegisterColorHandlersEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import fr.erinagroups.erinium.block.WizardBossSpawnerBlock;
import fr.erinagroups.erinium.block.UltimateLootboxBlock;
import fr.erinagroups.erinium.block.TourTradiBlock;
import fr.erinagroups.erinium.block.SpectriumOreBlock;
import fr.erinagroups.erinium.block.SpectriumBlockBlock;
import fr.erinagroups.erinium.block.SpectriumBatteryBlock;
import fr.erinagroups.erinium.block.SpatialTeleporterBlockBlock;
import fr.erinagroups.erinium.block.SilverOreBlock;
import fr.erinagroups.erinium.block.SiliconeOreBlock;
import fr.erinagroups.erinium.block.SetanumStage3Block;
import fr.erinagroups.erinium.block.SetanumStage2Block;
import fr.erinagroups.erinium.block.SetanumStage1Block;
import fr.erinagroups.erinium.block.SetanumStage0Block;
import fr.erinagroups.erinium.block.SetanumBlockBlock;
import fr.erinagroups.erinium.block.SciningSandstoneBlock;
import fr.erinagroups.erinium.block.SciningSandBlock;
import fr.erinagroups.erinium.block.SciningCactusBlock;
import fr.erinagroups.erinium.block.RockVolcanoBlock;
import fr.erinagroups.erinium.block.RedJungleGrassBlock;
import fr.erinagroups.erinium.block.RedJungleDirtBlock;
import fr.erinagroups.erinium.block.PrinterBlock;
import fr.erinagroups.erinium.block.NetherStarGenBlock;
import fr.erinagroups.erinium.block.MoonStoneBlock;
import fr.erinagroups.erinium.block.MoonSandBlock;
import fr.erinagroups.erinium.block.Line1BlockBlock;
import fr.erinagroups.erinium.block.LeatherBlockBlock;
import fr.erinagroups.erinium.block.LeadOreBlock;
import fr.erinagroups.erinium.block.LanternPlantBlock;
import fr.erinagroups.erinium.block.JLSkyzerPaintingBlock;
import fr.erinagroups.erinium.block.JLSkyzerPainting2Block;
import fr.erinagroups.erinium.block.IcyMushroomBlock;
import fr.erinagroups.erinium.block.House1BlockBlock;
import fr.erinagroups.erinium.block.HotWaterBlock;
import fr.erinagroups.erinium.block.FraisageNumeriqueBlock;
import fr.erinagroups.erinium.block.FonderieBlock;
import fr.erinagroups.erinium.block.ExtractorEmptyBlock;
import fr.erinagroups.erinium.block.ExtractorBottleEmptyBlock;
import fr.erinagroups.erinium.block.ExtractorAmenine5Block;
import fr.erinagroups.erinium.block.ExtractorAmenine4Block;
import fr.erinagroups.erinium.block.ExtractorAmenine3Block;
import fr.erinagroups.erinium.block.ExtractorAmenine2Block;
import fr.erinagroups.erinium.block.ExtractorAmenine1Block;
import fr.erinagroups.erinium.block.EriniumWorkbenchTier1Block;
import fr.erinagroups.erinium.block.EriniumOreMoonBlock;
import fr.erinagroups.erinium.block.EriniumOreBlock;
import fr.erinagroups.erinium.block.EriniumObsidianBlock;
import fr.erinagroups.erinium.block.EriniumMatrixBlockBlock;
import fr.erinagroups.erinium.block.EriniumLogoBlock;
import fr.erinagroups.erinium.block.EriniumCobwebBlock;
import fr.erinagroups.erinium.block.EriniumBushBlock;
import fr.erinagroups.erinium.block.EriniumBossSpawnerBlock;
import fr.erinagroups.erinium.block.EriniumBlockBlock;
import fr.erinagroups.erinium.block.EriniumBackgroundBlock;
import fr.erinagroups.erinium.block.EnergySellerBlock;
import fr.erinagroups.erinium.block.EggFactoryBlock;
import fr.erinagroups.erinium.block.DraniteOreBlock;
import fr.erinagroups.erinium.block.DeltaMarquedBlock;
import fr.erinagroups.erinium.block.CutoutblockBlock;
import fr.erinagroups.erinium.block.CopperOreBlock;
import fr.erinagroups.erinium.block.CobbleVoidStationBlock;
import fr.erinagroups.erinium.block.ClassicLootboxBlock;
import fr.erinagroups.erinium.block.ChocolateDirtBlock;
import fr.erinagroups.erinium.block.CharlieMarquedBlock;
import fr.erinagroups.erinium.block.CaveBlockBlock;
import fr.erinagroups.erinium.block.CandyStoneBlock;
import fr.erinagroups.erinium.block.CandyStairsBlock;
import fr.erinagroups.erinium.block.CandySlabBlock;
import fr.erinagroups.erinium.block.CandySilverOreBlock;
import fr.erinagroups.erinium.block.CandyRedstoneOreBlock;
import fr.erinagroups.erinium.block.CandyPlanksBlock;
import fr.erinagroups.erinium.block.CandyLogsBlock;
import fr.erinagroups.erinium.block.CandyLeavesBlock;
import fr.erinagroups.erinium.block.CandyLeadOreBlock;
import fr.erinagroups.erinium.block.CandyLapisOreBlock;
import fr.erinagroups.erinium.block.CandyIronOreBlock;
import fr.erinagroups.erinium.block.CandyGrassBlock;
import fr.erinagroups.erinium.block.CandyGoldOreBlock;
import fr.erinagroups.erinium.block.CandyEriniumOreBlock;
import fr.erinagroups.erinium.block.CandyEmeralOreBlock;
import fr.erinagroups.erinium.block.CandyDiamondOreBlock;
import fr.erinagroups.erinium.block.CandyCopperOreBlock;
import fr.erinagroups.erinium.block.CandyCobblestoneBlock;
import fr.erinagroups.erinium.block.CandyCoalOreBlock;
import fr.erinagroups.erinium.block.CandyBarBlock;
import fr.erinagroups.erinium.block.CalculatorBlock;
import fr.erinagroups.erinium.block.BushBlock;
import fr.erinagroups.erinium.block.BlockSetterBlock;
import fr.erinagroups.erinium.block.BlackMetalBlock;
import fr.erinagroups.erinium.block.BlackMetal2Block;
import fr.erinagroups.erinium.block.BlackBrickBlock;
import fr.erinagroups.erinium.block.BetaMarquedBlock;
import fr.erinagroups.erinium.block.AstralMinerBlock;
import fr.erinagroups.erinium.block.AmenineTrapdoorBlock;
import fr.erinagroups.erinium.block.AmenineStairsBlock;
import fr.erinagroups.erinium.block.AmenineSlabBlock;
import fr.erinagroups.erinium.block.AmenineRodBlock;
import fr.erinagroups.erinium.block.AmeninePressurePlateBlock;
import fr.erinagroups.erinium.block.AmeninePlanksBlock;
import fr.erinagroups.erinium.block.AmenineLogsBlock;
import fr.erinagroups.erinium.block.AmenineLeavesBlock;
import fr.erinagroups.erinium.block.AmenineFenceGateBlock;
import fr.erinagroups.erinium.block.AmenineFenceBlock;
import fr.erinagroups.erinium.block.AmenineButtonBlock;
import fr.erinagroups.erinium.block.AlphaMarquedBlock;
import fr.erinagroups.erinium.EriniumMod;

public class EriniumModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, EriniumMod.MODID);
	public static final RegistryObject<Block> ERINIUM_ORE = REGISTRY.register("erinium_ore", () -> new EriniumOreBlock());
	public static final RegistryObject<Block> SILICONE_ORE = REGISTRY.register("silicone_ore", () -> new SiliconeOreBlock());
	public static final RegistryObject<Block> DRANITE_ORE = REGISTRY.register("dranite_ore", () -> new DraniteOreBlock());
	public static final RegistryObject<Block> COPPER_ORE = REGISTRY.register("copper_ore", () -> new CopperOreBlock());
	public static final RegistryObject<Block> LEAD_ORE = REGISTRY.register("lead_ore", () -> new LeadOreBlock());
	public static final RegistryObject<Block> SILVER_ORE = REGISTRY.register("silver_ore", () -> new SilverOreBlock());
	public static final RegistryObject<Block> ERINIUM_ORE_MOON = REGISTRY.register("erinium_ore_moon", () -> new EriniumOreMoonBlock());
	public static final RegistryObject<Block> SPECTRIUM_ORE = REGISTRY.register("spectrium_ore", () -> new SpectriumOreBlock());
	public static final RegistryObject<Block> CANDY_COAL_ORE = REGISTRY.register("candy_coal_ore", () -> new CandyCoalOreBlock());
	public static final RegistryObject<Block> CANDY_IRON_ORE = REGISTRY.register("candy_iron_ore", () -> new CandyIronOreBlock());
	public static final RegistryObject<Block> CANDY_GOLD_ORE = REGISTRY.register("candy_gold_ore", () -> new CandyGoldOreBlock());
	public static final RegistryObject<Block> CANDY_REDSTONE_ORE = REGISTRY.register("candy_redstone_ore", () -> new CandyRedstoneOreBlock());
	public static final RegistryObject<Block> CANDY_DIAMOND_ORE = REGISTRY.register("candy_diamond_ore", () -> new CandyDiamondOreBlock());
	public static final RegistryObject<Block> CANDY_LAPIS_ORE = REGISTRY.register("candy_lapis_ore", () -> new CandyLapisOreBlock());
	public static final RegistryObject<Block> CANDY_EMERAL_ORE = REGISTRY.register("candy_emeral_ore", () -> new CandyEmeralOreBlock());
	public static final RegistryObject<Block> CANDY_ERINIUM_ORE = REGISTRY.register("candy_erinium_ore", () -> new CandyEriniumOreBlock());
	public static final RegistryObject<Block> CANDY_COPPER_ORE = REGISTRY.register("candy_copper_ore", () -> new CandyCopperOreBlock());
	public static final RegistryObject<Block> CANDY_SILVER_ORE = REGISTRY.register("candy_silver_ore", () -> new CandySilverOreBlock());
	public static final RegistryObject<Block> CANDY_LEAD_ORE = REGISTRY.register("candy_lead_ore", () -> new CandyLeadOreBlock());
	public static final RegistryObject<Block> ERINIUM_BLOCK = REGISTRY.register("erinium_block", () -> new EriniumBlockBlock());
	public static final RegistryObject<Block> ERINIUM_OBSIDIAN = REGISTRY.register("erinium_obsidian", () -> new EriniumObsidianBlock());
	public static final RegistryObject<Block> SETANUM_BLOCK = REGISTRY.register("setanum_block", () -> new SetanumBlockBlock());
	public static final RegistryObject<Block> CAVE_BLOCK = REGISTRY.register("cave_block", () -> new CaveBlockBlock());
	public static final RegistryObject<Block> SCINING_SAND = REGISTRY.register("scining_sand", () -> new SciningSandBlock());
	public static final RegistryObject<Block> SCINING_SANDSTONE = REGISTRY.register("scining_sandstone", () -> new SciningSandstoneBlock());
	public static final RegistryObject<Block> SCINING_CACTUS = REGISTRY.register("scining_cactus", () -> new SciningCactusBlock());
	public static final RegistryObject<Block> BUSH = REGISTRY.register("bush", () -> new BushBlock());
	public static final RegistryObject<Block> BLOCK_SETTER = REGISTRY.register("block_setter", () -> new BlockSetterBlock());
	public static final RegistryObject<Block> MOON_SAND = REGISTRY.register("moon_sand", () -> new MoonSandBlock());
	public static final RegistryObject<Block> MOON_STONE = REGISTRY.register("moon_stone", () -> new MoonStoneBlock());
	public static final RegistryObject<Block> CLASSIC_LOOTBOX = REGISTRY.register("classic_lootbox", () -> new ClassicLootboxBlock());
	public static final RegistryObject<Block> ULTIMATE_LOOTBOX = REGISTRY.register("ultimate_lootbox", () -> new UltimateLootboxBlock());
	public static final RegistryObject<Block> SPECTRIUM_BLOCK = REGISTRY.register("spectrium_block", () -> new SpectriumBlockBlock());
	public static final RegistryObject<Block> AMENINE_LOGS = REGISTRY.register("amenine_logs", () -> new AmenineLogsBlock());
	public static final RegistryObject<Block> AMENINE_LEAVES = REGISTRY.register("amenine_leaves", () -> new AmenineLeavesBlock());
	public static final RegistryObject<Block> AMENINE_PLANKS = REGISTRY.register("amenine_planks", () -> new AmeninePlanksBlock());
	public static final RegistryObject<Block> AMENINE_FENCE = REGISTRY.register("amenine_fence", () -> new AmenineFenceBlock());
	public static final RegistryObject<Block> AMENINE_FENCE_GATE = REGISTRY.register("amenine_fence_gate", () -> new AmenineFenceGateBlock());
	public static final RegistryObject<Block> AMENINE_STAIRS = REGISTRY.register("amenine_stairs", () -> new AmenineStairsBlock());
	public static final RegistryObject<Block> AMENINE_SLAB = REGISTRY.register("amenine_slab", () -> new AmenineSlabBlock());
	public static final RegistryObject<Block> AMENINE_TRAPDOOR = REGISTRY.register("amenine_trapdoor", () -> new AmenineTrapdoorBlock());
	public static final RegistryObject<Block> AMENINE_PRESSURE_PLATE = REGISTRY.register("amenine_pressure_plate", () -> new AmeninePressurePlateBlock());
	public static final RegistryObject<Block> AMENINE_BUTTON = REGISTRY.register("amenine_button", () -> new AmenineButtonBlock());
	public static final RegistryObject<Block> AMENINE_ROD = REGISTRY.register("amenine_rod", () -> new AmenineRodBlock());
	public static final RegistryObject<Block> ERINIUM_BOSS_SPAWNER = REGISTRY.register("erinium_boss_spawner", () -> new EriniumBossSpawnerBlock());
	public static final RegistryObject<Block> WIZARD_BOSS_SPAWNER = REGISTRY.register("wizard_boss_spawner", () -> new WizardBossSpawnerBlock());
	public static final RegistryObject<Block> LEATHER_BLOCK = REGISTRY.register("leather_block", () -> new LeatherBlockBlock());
	public static final RegistryObject<Block> BLACK_BRICK = REGISTRY.register("black_brick", () -> new BlackBrickBlock());
	public static final RegistryObject<Block> BLACK_METAL = REGISTRY.register("black_metal", () -> new BlackMetalBlock());
	public static final RegistryObject<Block> BLACK_METAL_2 = REGISTRY.register("black_metal_2", () -> new BlackMetal2Block());
	public static final RegistryObject<Block> CANDY_BAR = REGISTRY.register("candy_bar", () -> new CandyBarBlock());
	public static final RegistryObject<Block> CANDY_GRASS = REGISTRY.register("candy_grass", () -> new CandyGrassBlock());
	public static final RegistryObject<Block> CHOCOLATE_DIRT = REGISTRY.register("chocolate_dirt", () -> new ChocolateDirtBlock());
	public static final RegistryObject<Block> CANDY_LOGS = REGISTRY.register("candy_logs", () -> new CandyLogsBlock());
	public static final RegistryObject<Block> CANDY_LEAVES = REGISTRY.register("candy_leaves", () -> new CandyLeavesBlock());
	public static final RegistryObject<Block> CANDY_PLANKS = REGISTRY.register("candy_planks", () -> new CandyPlanksBlock());
	public static final RegistryObject<Block> CANDY_SLAB = REGISTRY.register("candy_slab", () -> new CandySlabBlock());
	public static final RegistryObject<Block> CANDY_STAIRS = REGISTRY.register("candy_stairs", () -> new CandyStairsBlock());
	public static final RegistryObject<Block> CANDY_COBBLESTONE = REGISTRY.register("candy_cobblestone", () -> new CandyCobblestoneBlock());
	public static final RegistryObject<Block> CANDY_STONE = REGISTRY.register("candy_stone", () -> new CandyStoneBlock());
	public static final RegistryObject<Block> ERINIUM_COBWEB = REGISTRY.register("erinium_cobweb", () -> new EriniumCobwebBlock());
	public static final RegistryObject<Block> CUTOUTBLOCK = REGISTRY.register("cutoutblock", () -> new CutoutblockBlock());
	public static final RegistryObject<Block> LINE_1_BLOCK = REGISTRY.register("line_1_block", () -> new Line1BlockBlock());
	public static final RegistryObject<Block> HOUSE_1_BLOCK = REGISTRY.register("house_1_block", () -> new House1BlockBlock());
	public static final RegistryObject<Block> CALCULATOR = REGISTRY.register("calculator", () -> new CalculatorBlock());
	public static final RegistryObject<Block> PRINTER = REGISTRY.register("printer", () -> new PrinterBlock());
	public static final RegistryObject<Block> SPATIAL_TELEPORTER_BLOCK = REGISTRY.register("spatial_teleporter_block", () -> new SpatialTeleporterBlockBlock());
	public static final RegistryObject<Block> TOUR_TRADI = REGISTRY.register("tour_tradi", () -> new TourTradiBlock());
	public static final RegistryObject<Block> EXTRACTOR_EMPTY = REGISTRY.register("extractor_empty", () -> new ExtractorEmptyBlock());
	public static final RegistryObject<Block> EXTRACTOR_BOTTLE_EMPTY = REGISTRY.register("extractor_bottle_empty", () -> new ExtractorBottleEmptyBlock());
	public static final RegistryObject<Block> EXTRACTOR_AMENINE_1 = REGISTRY.register("extractor_amenine_1", () -> new ExtractorAmenine1Block());
	public static final RegistryObject<Block> EXTRACTOR_AMENINE_2 = REGISTRY.register("extractor_amenine_2", () -> new ExtractorAmenine2Block());
	public static final RegistryObject<Block> EXTRACTOR_AMENINE_3 = REGISTRY.register("extractor_amenine_3", () -> new ExtractorAmenine3Block());
	public static final RegistryObject<Block> EXTRACTOR_AMENINE_4 = REGISTRY.register("extractor_amenine_4", () -> new ExtractorAmenine4Block());
	public static final RegistryObject<Block> EXTRACTOR_AMENINE_5 = REGISTRY.register("extractor_amenine_5", () -> new ExtractorAmenine5Block());
	public static final RegistryObject<Block> FRAISAGE_NUMERIQUE = REGISTRY.register("fraisage_numerique", () -> new FraisageNumeriqueBlock());
	public static final RegistryObject<Block> FONDERIE = REGISTRY.register("fonderie", () -> new FonderieBlock());
	public static final RegistryObject<Block> EGG_FACTORY = REGISTRY.register("egg_factory", () -> new EggFactoryBlock());
	public static final RegistryObject<Block> NETHER_STAR_GEN = REGISTRY.register("nether_star_gen", () -> new NetherStarGenBlock());
	public static final RegistryObject<Block> ERINIUM_BUSH = REGISTRY.register("erinium_bush", () -> new EriniumBushBlock());
	public static final RegistryObject<Block> SETANUM_STAGE_0 = REGISTRY.register("setanum_stage_0", () -> new SetanumStage0Block());
	public static final RegistryObject<Block> SETANUM_STAGE_1 = REGISTRY.register("setanum_stage_1", () -> new SetanumStage1Block());
	public static final RegistryObject<Block> SETANUM_STAGE_2 = REGISTRY.register("setanum_stage_2", () -> new SetanumStage2Block());
	public static final RegistryObject<Block> SETANUM_STAGE_3 = REGISTRY.register("setanum_stage_3", () -> new SetanumStage3Block());
	public static final RegistryObject<Block> ALPHA_MARQUED = REGISTRY.register("alpha_marqued", () -> new AlphaMarquedBlock());
	public static final RegistryObject<Block> BETA_MARQUED = REGISTRY.register("beta_marqued", () -> new BetaMarquedBlock());
	public static final RegistryObject<Block> CHARLIE_MARQUED = REGISTRY.register("charlie_marqued", () -> new CharlieMarquedBlock());
	public static final RegistryObject<Block> DELTA_MARQUED = REGISTRY.register("delta_marqued", () -> new DeltaMarquedBlock());
	public static final RegistryObject<Block> JL_SKYZER_PAINTING = REGISTRY.register("jl_skyzer_painting", () -> new JLSkyzerPaintingBlock());
	public static final RegistryObject<Block> JL_SKYZER_PAINTING_2 = REGISTRY.register("jl_skyzer_painting_2", () -> new JLSkyzerPainting2Block());
	public static final RegistryObject<Block> ERINIUM_BACKGROUND = REGISTRY.register("erinium_background", () -> new EriniumBackgroundBlock());
	public static final RegistryObject<Block> ERINIUM_LOGO = REGISTRY.register("erinium_logo", () -> new EriniumLogoBlock());
	public static final RegistryObject<Block> SPECTRIUM_BATTERY = REGISTRY.register("spectrium_battery", () -> new SpectriumBatteryBlock());
	public static final RegistryObject<Block> ERINIUM_WORKBENCH_TIER_1 = REGISTRY.register("erinium_workbench_tier_1", () -> new EriniumWorkbenchTier1Block());
	public static final RegistryObject<Block> ERINIUM_MATRIX_BLOCK = REGISTRY.register("erinium_matrix_block", () -> new EriniumMatrixBlockBlock());
	public static final RegistryObject<Block> ICY_MUSHROOM = REGISTRY.register("icy_mushroom", () -> new IcyMushroomBlock());
	public static final RegistryObject<Block> LANTERN_PLANT = REGISTRY.register("lantern_plant", () -> new LanternPlantBlock());
	public static final RegistryObject<Block> HOT_WATER = REGISTRY.register("hot_water", () -> new HotWaterBlock());
	public static final RegistryObject<Block> RED_JUNGLE_DIRT = REGISTRY.register("red_jungle_dirt", () -> new RedJungleDirtBlock());
	public static final RegistryObject<Block> RED_JUNGLE_GRASS = REGISTRY.register("red_jungle_grass", () -> new RedJungleGrassBlock());
	public static final RegistryObject<Block> ROCK_VOLCANO = REGISTRY.register("rock_volcano", () -> new RockVolcanoBlock());
	public static final RegistryObject<Block> ASTRAL_MINER = REGISTRY.register("astral_miner", () -> new AstralMinerBlock());
	public static final RegistryObject<Block> COBBLE_VOID_STATION = REGISTRY.register("cobble_void_station", () -> new CobbleVoidStationBlock());
	public static final RegistryObject<Block> ENERGY_SELLER = REGISTRY.register("energy_seller", () -> new EnergySellerBlock());

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			EriniumBushBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(RegisterColorHandlersEvent.Item event) {
			EriniumBushBlock.itemColorLoad(event);
		}
	}
}
