
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package fr.erinagroups.erinium.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import fr.erinagroups.erinium.item.XpLargeBottleItem;
import fr.erinagroups.erinium.item.XpEssenceItem;
import fr.erinagroups.erinium.item.WiringKitItem;
import fr.erinagroups.erinium.item.WarningLogoItem;
import fr.erinagroups.erinium.item.UsinageItem;
import fr.erinagroups.erinium.item.TreeBossShardItem;
import fr.erinagroups.erinium.item.TreeBossProjectileItem;
import fr.erinagroups.erinium.item.TreeBossArmorItem;
import fr.erinagroups.erinium.item.Tier1CraftingBenchItem;
import fr.erinagroups.erinium.item.SpectriumGemItem;
import fr.erinagroups.erinium.item.SpectiumArmorItem;
import fr.erinagroups.erinium.item.SoulBottleItem;
import fr.erinagroups.erinium.item.SoulBottle5Item;
import fr.erinagroups.erinium.item.SoulBottle4Item;
import fr.erinagroups.erinium.item.SoulBottle3Item;
import fr.erinagroups.erinium.item.SoulBottle2Item;
import fr.erinagroups.erinium.item.SoulBottle1Item;
import fr.erinagroups.erinium.item.SkeletonShardItem;
import fr.erinagroups.erinium.item.SkeletonNuggetsItem;
import fr.erinagroups.erinium.item.SilverIngotItem;
import fr.erinagroups.erinium.item.SiliconeFragmentItem;
import fr.erinagroups.erinium.item.SetanumSwordItem;
import fr.erinagroups.erinium.item.SetanumShovelItem;
import fr.erinagroups.erinium.item.SetanumSeedsItem;
import fr.erinagroups.erinium.item.SetanumPickaxeItem;
import fr.erinagroups.erinium.item.SetanumNuggetsItem;
import fr.erinagroups.erinium.item.SetanumItem;
import fr.erinagroups.erinium.item.SetanumIngotItem;
import fr.erinagroups.erinium.item.SetanumAxeItem;
import fr.erinagroups.erinium.item.ScreenItem;
import fr.erinagroups.erinium.item.SciningGlassFragmentItem;
import fr.erinagroups.erinium.item.RubberItem;
import fr.erinagroups.erinium.item.RainbowSwordItem;
import fr.erinagroups.erinium.item.RainbowShovelItem;
import fr.erinagroups.erinium.item.RainbowPickaxeItem;
import fr.erinagroups.erinium.item.RainbowAxeItem;
import fr.erinagroups.erinium.item.PureGemItem;
import fr.erinagroups.erinium.item.PrintedCircuitBoardItem;
import fr.erinagroups.erinium.item.OpToolItem;
import fr.erinagroups.erinium.item.MagicalWandItem;
import fr.erinagroups.erinium.item.MagicWandItem;
import fr.erinagroups.erinium.item.MagicWandCobwebItem;
import fr.erinagroups.erinium.item.MagicStonesXpItem;
import fr.erinagroups.erinium.item.MagicStonesTeleportationItem;
import fr.erinagroups.erinium.item.MagicStonesRegeneratiobItem;
import fr.erinagroups.erinium.item.MagicStonesInvisibilityItem;
import fr.erinagroups.erinium.item.MagicStonesHealItem;
import fr.erinagroups.erinium.item.MagicStonesDebugItem;
import fr.erinagroups.erinium.item.MagicStonesDamageItem;
import fr.erinagroups.erinium.item.MagicStonesCreditItem;
import fr.erinagroups.erinium.item.MagicStickItem;
import fr.erinagroups.erinium.item.MagicOrbItem;
import fr.erinagroups.erinium.item.LeadIngotItem;
import fr.erinagroups.erinium.item.LaserDrillItem;
import fr.erinagroups.erinium.item.KnifeToolItem;
import fr.erinagroups.erinium.item.KnifeItem;
import fr.erinagroups.erinium.item.ItemPosItem;
import fr.erinagroups.erinium.item.HotWaterItem;
import fr.erinagroups.erinium.item.HomeTeleporterItem;
import fr.erinagroups.erinium.item.HackedUsbKeyItem;
import fr.erinagroups.erinium.item.GemXpItem;
import fr.erinagroups.erinium.item.GemTeleportItem;
import fr.erinagroups.erinium.item.GemRegenerationItem;
import fr.erinagroups.erinium.item.GemInvisibilityItem;
import fr.erinagroups.erinium.item.GemHealItem;
import fr.erinagroups.erinium.item.GemDamageItem;
import fr.erinagroups.erinium.item.GemCreditItem;
import fr.erinagroups.erinium.item.FraisageItem;
import fr.erinagroups.erinium.item.FortuneModifierItem;
import fr.erinagroups.erinium.item.FakeEriniumIngotItem;
import fr.erinagroups.erinium.item.FabricRollItem;
import fr.erinagroups.erinium.item.EriniumTabAnimationItem;
import fr.erinagroups.erinium.item.EriniumSwordItem;
import fr.erinagroups.erinium.item.EriniumStickItem;
import fr.erinagroups.erinium.item.EriniumPickaxeItem;
import fr.erinagroups.erinium.item.EriniumMatrixSwordItem;
import fr.erinagroups.erinium.item.EriniumMatrixPickaxeItem;
import fr.erinagroups.erinium.item.EriniumMatrixIngotItem;
import fr.erinagroups.erinium.item.EriniumMatrixAxeItem;
import fr.erinagroups.erinium.item.EriniumMatrixArmorItem;
import fr.erinagroups.erinium.item.EriniumIngotItem;
import fr.erinagroups.erinium.item.EriniumHammerItem;
import fr.erinagroups.erinium.item.EriniumAxeItem;
import fr.erinagroups.erinium.item.EriniumArmorItem;
import fr.erinagroups.erinium.item.EmptyLargeBottleItem;
import fr.erinagroups.erinium.item.EmptyBottleItem;
import fr.erinagroups.erinium.item.EmptyBoardItem;
import fr.erinagroups.erinium.item.DungeonFinderItem;
import fr.erinagroups.erinium.item.DraniteGemItem;
import fr.erinagroups.erinium.item.CopperIngotItem;
import fr.erinagroups.erinium.item.CobbleVoidItem;
import fr.erinagroups.erinium.item.ChestFinderItem;
import fr.erinagroups.erinium.item.CardboardRollItem;
import fr.erinagroups.erinium.item.CardboardItem;
import fr.erinagroups.erinium.item.BombItem;
import fr.erinagroups.erinium.item.BloodOrbItem;
import fr.erinagroups.erinium.item.BloodLargeBottleItem;
import fr.erinagroups.erinium.item.BlockReplacerItem;
import fr.erinagroups.erinium.item.BedrockStickItem;
import fr.erinagroups.erinium.item.AstralMinerLaserModuleItem;
import fr.erinagroups.erinium.item.AstralMinerFootItem;
import fr.erinagroups.erinium.item.AmenineStickItem;
import fr.erinagroups.erinium.item.AmenineLiquid5Item;
import fr.erinagroups.erinium.item.AmenineLiquid4Item;
import fr.erinagroups.erinium.item.AmenineLiquid3Item;
import fr.erinagroups.erinium.item.AmenineLiquid2Item;
import fr.erinagroups.erinium.item.AmenineLiquid1Item;
import fr.erinagroups.erinium.item.AlmoniePaperItem;
import fr.erinagroups.erinium.item.AlmonieGemItem;
import fr.erinagroups.erinium.item.AlmonieCardItem;
import fr.erinagroups.erinium.item.AdminStickItem;
import fr.erinagroups.erinium.EriniumMod;

public class EriniumModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, EriniumMod.MODID);
	public static final RegistryObject<Item> ERINIUM_ARMOR_HELMET = REGISTRY.register("erinium_armor_helmet", () -> new EriniumArmorItem.Helmet());
	public static final RegistryObject<Item> ERINIUM_ARMOR_CHESTPLATE = REGISTRY.register("erinium_armor_chestplate", () -> new EriniumArmorItem.Chestplate());
	public static final RegistryObject<Item> ERINIUM_ARMOR_LEGGINGS = REGISTRY.register("erinium_armor_leggings", () -> new EriniumArmorItem.Leggings());
	public static final RegistryObject<Item> ERINIUM_ARMOR_BOOTS = REGISTRY.register("erinium_armor_boots", () -> new EriniumArmorItem.Boots());
	public static final RegistryObject<Item> SETANUM_HELMET = REGISTRY.register("setanum_helmet", () -> new SetanumItem.Helmet());
	public static final RegistryObject<Item> SETANUM_CHESTPLATE = REGISTRY.register("setanum_chestplate", () -> new SetanumItem.Chestplate());
	public static final RegistryObject<Item> SETANUM_LEGGINGS = REGISTRY.register("setanum_leggings", () -> new SetanumItem.Leggings());
	public static final RegistryObject<Item> SETANUM_BOOTS = REGISTRY.register("setanum_boots", () -> new SetanumItem.Boots());
	public static final RegistryObject<Item> TREE_BOSS_ARMOR_HELMET = REGISTRY.register("tree_boss_armor_helmet", () -> new TreeBossArmorItem.Helmet());
	public static final RegistryObject<Item> TREE_BOSS_ARMOR_CHESTPLATE = REGISTRY.register("tree_boss_armor_chestplate", () -> new TreeBossArmorItem.Chestplate());
	public static final RegistryObject<Item> TREE_BOSS_ARMOR_LEGGINGS = REGISTRY.register("tree_boss_armor_leggings", () -> new TreeBossArmorItem.Leggings());
	public static final RegistryObject<Item> TREE_BOSS_ARMOR_BOOTS = REGISTRY.register("tree_boss_armor_boots", () -> new TreeBossArmorItem.Boots());
	public static final RegistryObject<Item> SPECTIUM_ARMOR_HELMET = REGISTRY.register("spectium_armor_helmet", () -> new SpectiumArmorItem.Helmet());
	public static final RegistryObject<Item> SPECTIUM_ARMOR_CHESTPLATE = REGISTRY.register("spectium_armor_chestplate", () -> new SpectiumArmorItem.Chestplate());
	public static final RegistryObject<Item> SPECTIUM_ARMOR_LEGGINGS = REGISTRY.register("spectium_armor_leggings", () -> new SpectiumArmorItem.Leggings());
	public static final RegistryObject<Item> SPECTIUM_ARMOR_BOOTS = REGISTRY.register("spectium_armor_boots", () -> new SpectiumArmorItem.Boots());
	public static final RegistryObject<Item> ERINIUM_SWORD = REGISTRY.register("erinium_sword", () -> new EriniumSwordItem());
	public static final RegistryObject<Item> ERINIUM_AXE = REGISTRY.register("erinium_axe", () -> new EriniumAxeItem());
	public static final RegistryObject<Item> ERINIUM_PICKAXE = REGISTRY.register("erinium_pickaxe", () -> new EriniumPickaxeItem());
	public static final RegistryObject<Item> ERINIUM_HAMMER = REGISTRY.register("erinium_hammer", () -> new EriniumHammerItem());
	public static final RegistryObject<Item> MAGIC_WAND = REGISTRY.register("magic_wand", () -> new MagicWandItem());
	public static final RegistryObject<Item> SETANUM_SWORD = REGISTRY.register("setanum_sword", () -> new SetanumSwordItem());
	public static final RegistryObject<Item> SETANUM_PICKAXE = REGISTRY.register("setanum_pickaxe", () -> new SetanumPickaxeItem());
	public static final RegistryObject<Item> SETANUM_AXE = REGISTRY.register("setanum_axe", () -> new SetanumAxeItem());
	public static final RegistryObject<Item> SETANUM_SHOVEL = REGISTRY.register("setanum_shovel", () -> new SetanumShovelItem());
	public static final RegistryObject<Item> BEDROCK_STICK = REGISTRY.register("bedrock_stick", () -> new BedrockStickItem());
	public static final RegistryObject<Item> KNIFE = REGISTRY.register("knife", () -> new KnifeItem());
	public static final RegistryObject<Item> KNIFE_TOOL = REGISTRY.register("knife_tool", () -> new KnifeToolItem());
	public static final RegistryObject<Item> BLOCK_REPLACER = REGISTRY.register("block_replacer", () -> new BlockReplacerItem());
	public static final RegistryObject<Item> CHEST_FINDER = REGISTRY.register("chest_finder", () -> new ChestFinderItem());
	public static final RegistryObject<Item> DUNGEON_FINDER = REGISTRY.register("dungeon_finder", () -> new DungeonFinderItem());
	public static final RegistryObject<Item> COBBLE_VOID = REGISTRY.register("cobble_void", () -> new CobbleVoidItem());
	public static final RegistryObject<Item> HOME_TELEPORTER = REGISTRY.register("home_teleporter", () -> new HomeTeleporterItem());
	public static final RegistryObject<Item> ERINIUM_INGOT = REGISTRY.register("erinium_ingot", () -> new EriniumIngotItem());
	public static final RegistryObject<Item> FAKE_ERINIUM_INGOT = REGISTRY.register("fake_erinium_ingot", () -> new FakeEriniumIngotItem());
	public static final RegistryObject<Item> SETANUM_INGOT = REGISTRY.register("setanum_ingot", () -> new SetanumIngotItem());
	public static final RegistryObject<Item> COPPER_INGOT = REGISTRY.register("copper_ingot", () -> new CopperIngotItem());
	public static final RegistryObject<Item> LEAD_INGOT = REGISTRY.register("lead_ingot", () -> new LeadIngotItem());
	public static final RegistryObject<Item> SILVER_INGOT = REGISTRY.register("silver_ingot", () -> new SilverIngotItem());
	public static final RegistryObject<Item> DRANITE_GEM = REGISTRY.register("dranite_gem", () -> new DraniteGemItem());
	public static final RegistryObject<Item> RUBBER = REGISTRY.register("rubber", () -> new RubberItem());
	public static final RegistryObject<Item> SPECTRIUM_GEM = REGISTRY.register("spectrium_gem", () -> new SpectriumGemItem());
	public static final RegistryObject<Item> SILICONE_FRAGMENT = REGISTRY.register("silicone_fragment", () -> new SiliconeFragmentItem());
	public static final RegistryObject<Item> TREE_BOSS_SHARD = REGISTRY.register("tree_boss_shard", () -> new TreeBossShardItem());
	public static final RegistryObject<Item> SETANUM_NUGGETS = REGISTRY.register("setanum_nuggets", () -> new SetanumNuggetsItem());
	public static final RegistryObject<Item> SKELETON_SHARD = REGISTRY.register("skeleton_shard", () -> new SkeletonShardItem());
	public static final RegistryObject<Item> SKELETON_NUGGETS = REGISTRY.register("skeleton_nuggets", () -> new SkeletonNuggetsItem());
	public static final RegistryObject<Item> SCINING_GLASS_FRAGMENT = REGISTRY.register("scining_glass_fragment", () -> new SciningGlassFragmentItem());
	public static final RegistryObject<Item> SETANUM_SEEDS = REGISTRY.register("setanum_seeds", () -> new SetanumSeedsItem());
	public static final RegistryObject<Item> XP_ESSENCE = REGISTRY.register("xp_essence", () -> new XpEssenceItem());
	public static final RegistryObject<Item> EMPTY_BOTTLE = REGISTRY.register("empty_bottle", () -> new EmptyBottleItem());
	public static final RegistryObject<Item> EMPTY_LARGE_BOTTLE = REGISTRY.register("empty_large_bottle", () -> new EmptyLargeBottleItem());
	public static final RegistryObject<Item> XP_LARGE_BOTTLE = REGISTRY.register("xp_large_bottle", () -> new XpLargeBottleItem());
	public static final RegistryObject<Item> BLOOD_LARGE_BOTTLE = REGISTRY.register("blood_large_bottle", () -> new BloodLargeBottleItem());
	public static final RegistryObject<Item> SOUL_BOTTLE = REGISTRY.register("soul_bottle", () -> new SoulBottleItem());
	public static final RegistryObject<Item> SOUL_BOTTLE_1 = REGISTRY.register("soul_bottle_1", () -> new SoulBottle1Item());
	public static final RegistryObject<Item> SOUL_BOTTLE_2 = REGISTRY.register("soul_bottle_2", () -> new SoulBottle2Item());
	public static final RegistryObject<Item> SOUL_BOTTLE_4 = REGISTRY.register("soul_bottle_4", () -> new SoulBottle4Item());
	public static final RegistryObject<Item> SOUL_BOTTLE_3 = REGISTRY.register("soul_bottle_3", () -> new SoulBottle3Item());
	public static final RegistryObject<Item> SOUL_BOTTLE_5 = REGISTRY.register("soul_bottle_5", () -> new SoulBottle5Item());
	public static final RegistryObject<Item> AMENINE_LIQUID_1 = REGISTRY.register("amenine_liquid_1", () -> new AmenineLiquid1Item());
	public static final RegistryObject<Item> AMENINE_LIQUID_2 = REGISTRY.register("amenine_liquid_2", () -> new AmenineLiquid2Item());
	public static final RegistryObject<Item> AMENINE_LIQUID_3 = REGISTRY.register("amenine_liquid_3", () -> new AmenineLiquid3Item());
	public static final RegistryObject<Item> AMENINE_LIQUID_4 = REGISTRY.register("amenine_liquid_4", () -> new AmenineLiquid4Item());
	public static final RegistryObject<Item> AMENINE_LIQUID_5 = REGISTRY.register("amenine_liquid_5", () -> new AmenineLiquid5Item());
	public static final RegistryObject<Item> MAGIC_STICK = REGISTRY.register("magic_stick", () -> new MagicStickItem());
	public static final RegistryObject<Item> ERINIUM_STICK = REGISTRY.register("erinium_stick", () -> new EriniumStickItem());
	public static final RegistryObject<Item> AMENINE_STICK = REGISTRY.register("amenine_stick", () -> new AmenineStickItem());
	public static final RegistryObject<Item> FORTUNE_MODIFIER = REGISTRY.register("fortune_modifier", () -> new FortuneModifierItem());
	public static final RegistryObject<Item> CARDBOARD = REGISTRY.register("cardboard", () -> new CardboardItem());
	public static final RegistryObject<Item> CARDBOARD_ROLL = REGISTRY.register("cardboard_roll", () -> new CardboardRollItem());
	public static final RegistryObject<Item> FABRIC_ROLL = REGISTRY.register("fabric_roll", () -> new FabricRollItem());
	public static final RegistryObject<Item> PRINTED_CIRCUIT_BOARD = REGISTRY.register("printed_circuit_board", () -> new PrintedCircuitBoardItem());
	public static final RegistryObject<Item> EMPTY_BOARD = REGISTRY.register("empty_board", () -> new EmptyBoardItem());
	public static final RegistryObject<Item> SCREEN = REGISTRY.register("screen", () -> new ScreenItem());
	public static final RegistryObject<Item> WIRING_KIT = REGISTRY.register("wiring_kit", () -> new WiringKitItem());
	public static final RegistryObject<Item> MAGIC_ORB = REGISTRY.register("magic_orb", () -> new MagicOrbItem());
	public static final RegistryObject<Item> MAGIC_STONES_INVISIBILITY = REGISTRY.register("magic_stones_invisibility", () -> new MagicStonesInvisibilityItem());
	public static final RegistryObject<Item> MAGIC_STONES_TELEPORTATION = REGISTRY.register("magic_stones_teleportation", () -> new MagicStonesTeleportationItem());
	public static final RegistryObject<Item> MAGIC_STONES_HEAL = REGISTRY.register("magic_stones_heal", () -> new MagicStonesHealItem());
	public static final RegistryObject<Item> MAGIC_STONES_REGENERATION = REGISTRY.register("magic_stones_regeneration", () -> new MagicStonesRegeneratiobItem());
	public static final RegistryObject<Item> MAGIC_STONES_DAMAGE = REGISTRY.register("magic_stones_damage", () -> new MagicStonesDamageItem());
	public static final RegistryObject<Item> MAGIC_STONES_XP = REGISTRY.register("magic_stones_xp", () -> new MagicStonesXpItem());
	public static final RegistryObject<Item> MAGIC_STONES_CREDIT = REGISTRY.register("magic_stones_credit", () -> new MagicStonesCreditItem());
	public static final RegistryObject<Item> PURE_GEM = REGISTRY.register("pure_gem", () -> new PureGemItem());
	public static final RegistryObject<Item> GEM_INVISIBILITY = REGISTRY.register("gem_invisibility", () -> new GemInvisibilityItem());
	public static final RegistryObject<Item> GEM_TELEPORT = REGISTRY.register("gem_teleport", () -> new GemTeleportItem());
	public static final RegistryObject<Item> GEM_HEAL = REGISTRY.register("gem_heal", () -> new GemHealItem());
	public static final RegistryObject<Item> GEM_REGENERATION = REGISTRY.register("gem_regeneration", () -> new GemRegenerationItem());
	public static final RegistryObject<Item> GEM_DAMAGE = REGISTRY.register("gem_damage", () -> new GemDamageItem());
	public static final RegistryObject<Item> GEM_XP = REGISTRY.register("gem_xp", () -> new GemXpItem());
	public static final RegistryObject<Item> GEM_CREDIT = REGISTRY.register("gem_credit", () -> new GemCreditItem());
	public static final RegistryObject<Item> ERINIUM_ORE = block(EriniumModBlocks.ERINIUM_ORE);
	public static final RegistryObject<Item> SILICONE_ORE = block(EriniumModBlocks.SILICONE_ORE);
	public static final RegistryObject<Item> DRANITE_ORE = block(EriniumModBlocks.DRANITE_ORE);
	public static final RegistryObject<Item> COPPER_ORE = block(EriniumModBlocks.COPPER_ORE);
	public static final RegistryObject<Item> LEAD_ORE = block(EriniumModBlocks.LEAD_ORE);
	public static final RegistryObject<Item> SILVER_ORE = block(EriniumModBlocks.SILVER_ORE);
	public static final RegistryObject<Item> ERINIUM_ORE_MOON = block(EriniumModBlocks.ERINIUM_ORE_MOON);
	public static final RegistryObject<Item> SPECTRIUM_ORE = block(EriniumModBlocks.SPECTRIUM_ORE);
	public static final RegistryObject<Item> CANDY_COAL_ORE = block(EriniumModBlocks.CANDY_COAL_ORE);
	public static final RegistryObject<Item> CANDY_IRON_ORE = block(EriniumModBlocks.CANDY_IRON_ORE);
	public static final RegistryObject<Item> CANDY_GOLD_ORE = block(EriniumModBlocks.CANDY_GOLD_ORE);
	public static final RegistryObject<Item> CANDY_REDSTONE_ORE = block(EriniumModBlocks.CANDY_REDSTONE_ORE);
	public static final RegistryObject<Item> CANDY_DIAMOND_ORE = block(EriniumModBlocks.CANDY_DIAMOND_ORE);
	public static final RegistryObject<Item> CANDY_LAPIS_ORE = block(EriniumModBlocks.CANDY_LAPIS_ORE);
	public static final RegistryObject<Item> CANDY_EMERAL_ORE = block(EriniumModBlocks.CANDY_EMERAL_ORE);
	public static final RegistryObject<Item> CANDY_ERINIUM_ORE = block(EriniumModBlocks.CANDY_ERINIUM_ORE);
	public static final RegistryObject<Item> CANDY_COPPER_ORE = block(EriniumModBlocks.CANDY_COPPER_ORE);
	public static final RegistryObject<Item> CANDY_SILVER_ORE = block(EriniumModBlocks.CANDY_SILVER_ORE);
	public static final RegistryObject<Item> CANDY_LEAD_ORE = block(EriniumModBlocks.CANDY_LEAD_ORE);
	public static final RegistryObject<Item> ERINIUM_BLOCK = block(EriniumModBlocks.ERINIUM_BLOCK);
	public static final RegistryObject<Item> ERINIUM_OBSIDIAN = block(EriniumModBlocks.ERINIUM_OBSIDIAN);
	public static final RegistryObject<Item> SETANUM_BLOCK = block(EriniumModBlocks.SETANUM_BLOCK);
	public static final RegistryObject<Item> CAVE_BLOCK = block(EriniumModBlocks.CAVE_BLOCK);
	public static final RegistryObject<Item> SCINING_SAND = block(EriniumModBlocks.SCINING_SAND);
	public static final RegistryObject<Item> SCINING_SANDSTONE = block(EriniumModBlocks.SCINING_SANDSTONE);
	public static final RegistryObject<Item> SCINING_CACTUS = block(EriniumModBlocks.SCINING_CACTUS);
	public static final RegistryObject<Item> BUSH = block(EriniumModBlocks.BUSH);
	public static final RegistryObject<Item> BLOCK_SETTER = block(EriniumModBlocks.BLOCK_SETTER);
	public static final RegistryObject<Item> MOON_SAND = block(EriniumModBlocks.MOON_SAND);
	public static final RegistryObject<Item> MOON_STONE = block(EriniumModBlocks.MOON_STONE);
	public static final RegistryObject<Item> CLASSIC_LOOTBOX = block(EriniumModBlocks.CLASSIC_LOOTBOX);
	public static final RegistryObject<Item> ULTIMATE_LOOTBOX = block(EriniumModBlocks.ULTIMATE_LOOTBOX);
	public static final RegistryObject<Item> SPECTRIUM_BLOCK = block(EriniumModBlocks.SPECTRIUM_BLOCK);
	public static final RegistryObject<Item> AMENINE_LOGS = block(EriniumModBlocks.AMENINE_LOGS);
	public static final RegistryObject<Item> AMENINE_LEAVES = block(EriniumModBlocks.AMENINE_LEAVES);
	public static final RegistryObject<Item> AMENINE_PLANKS = block(EriniumModBlocks.AMENINE_PLANKS);
	public static final RegistryObject<Item> AMENINE_FENCE = block(EriniumModBlocks.AMENINE_FENCE);
	public static final RegistryObject<Item> AMENINE_FENCE_GATE = block(EriniumModBlocks.AMENINE_FENCE_GATE);
	public static final RegistryObject<Item> AMENINE_STAIRS = block(EriniumModBlocks.AMENINE_STAIRS);
	public static final RegistryObject<Item> AMENINE_SLAB = block(EriniumModBlocks.AMENINE_SLAB);
	public static final RegistryObject<Item> AMENINE_TRAPDOOR = block(EriniumModBlocks.AMENINE_TRAPDOOR);
	public static final RegistryObject<Item> AMENINE_PRESSURE_PLATE = block(EriniumModBlocks.AMENINE_PRESSURE_PLATE);
	public static final RegistryObject<Item> AMENINE_BUTTON = block(EriniumModBlocks.AMENINE_BUTTON);
	public static final RegistryObject<Item> AMENINE_ROD = block(EriniumModBlocks.AMENINE_ROD);
	public static final RegistryObject<Item> ERINIUM_BOSS_SPAWNER = block(EriniumModBlocks.ERINIUM_BOSS_SPAWNER);
	public static final RegistryObject<Item> WIZARD_BOSS_SPAWNER = block(EriniumModBlocks.WIZARD_BOSS_SPAWNER);
	public static final RegistryObject<Item> LEATHER_BLOCK = block(EriniumModBlocks.LEATHER_BLOCK);
	public static final RegistryObject<Item> BLACK_BRICK = block(EriniumModBlocks.BLACK_BRICK);
	public static final RegistryObject<Item> BLACK_METAL = block(EriniumModBlocks.BLACK_METAL);
	public static final RegistryObject<Item> BLACK_METAL_2 = block(EriniumModBlocks.BLACK_METAL_2);
	public static final RegistryObject<Item> CANDY_BAR = block(EriniumModBlocks.CANDY_BAR);
	public static final RegistryObject<Item> CANDY_GRASS = block(EriniumModBlocks.CANDY_GRASS);
	public static final RegistryObject<Item> CHOCOLATE_DIRT = block(EriniumModBlocks.CHOCOLATE_DIRT);
	public static final RegistryObject<Item> CANDY_LOGS = block(EriniumModBlocks.CANDY_LOGS);
	public static final RegistryObject<Item> CANDY_LEAVES = block(EriniumModBlocks.CANDY_LEAVES);
	public static final RegistryObject<Item> CANDY_PLANKS = block(EriniumModBlocks.CANDY_PLANKS);
	public static final RegistryObject<Item> CANDY_SLAB = block(EriniumModBlocks.CANDY_SLAB);
	public static final RegistryObject<Item> CANDY_STAIRS = block(EriniumModBlocks.CANDY_STAIRS);
	public static final RegistryObject<Item> CANDY_COBBLESTONE = block(EriniumModBlocks.CANDY_COBBLESTONE);
	public static final RegistryObject<Item> CANDY_STONE = block(EriniumModBlocks.CANDY_STONE);
	public static final RegistryObject<Item> ERINIUM_COBWEB = block(EriniumModBlocks.ERINIUM_COBWEB);
	public static final RegistryObject<Item> OP_TOOL = REGISTRY.register("op_tool", () -> new OpToolItem());
	public static final RegistryObject<Item> ADMIN_STICK = REGISTRY.register("admin_stick", () -> new AdminStickItem());
	public static final RegistryObject<Item> CUTOUTBLOCK = block(EriniumModBlocks.CUTOUTBLOCK);
	public static final RegistryObject<Item> LINE_1_BLOCK = block(EriniumModBlocks.LINE_1_BLOCK);
	public static final RegistryObject<Item> HOUSE_1_BLOCK = block(EriniumModBlocks.HOUSE_1_BLOCK);
	public static final RegistryObject<Item> CALCULATOR = block(EriniumModBlocks.CALCULATOR);
	public static final RegistryObject<Item> ITEM_POS = REGISTRY.register("item_pos", () -> new ItemPosItem());
	public static final RegistryObject<Item> BOMB = REGISTRY.register("bomb", () -> new BombItem());
	public static final RegistryObject<Item> MAGIC_STONES_DEBUG = REGISTRY.register("magic_stones_debug", () -> new MagicStonesDebugItem());
	public static final RegistryObject<Item> GOMY_SPAWN_EGG = REGISTRY.register("gomy_spawn_egg", () -> new ForgeSpawnEggItem(EriniumModEntities.GOMY, -1, -6750208, new Item.Properties()));
	public static final RegistryObject<Item> ERINIUM_SKELETON_BOSS_SPAWN_EGG = REGISTRY.register("erinium_skeleton_boss_spawn_egg", () -> new ForgeSpawnEggItem(EriniumModEntities.ERINIUM_SKELETON_BOSS, -4586235, -15855083, new Item.Properties()));
	public static final RegistryObject<Item> USINAGE = REGISTRY.register("usinage", () -> new UsinageItem());
	public static final RegistryObject<Item> FRAISAGE = REGISTRY.register("fraisage", () -> new FraisageItem());
	public static final RegistryObject<Item> WIZARD_SPAWN_EGG = REGISTRY.register("wizard_spawn_egg", () -> new ForgeSpawnEggItem(EriniumModEntities.WIZARD, -16737793, -16763956, new Item.Properties()));
	public static final RegistryObject<Item> TREE_BOSS_SPAWN_EGG = REGISTRY.register("tree_boss_spawn_egg", () -> new ForgeSpawnEggItem(EriniumModEntities.TREE_BOSS, -16737997, -10079488, new Item.Properties()));
	public static final RegistryObject<Item> PRINTER = block(EriniumModBlocks.PRINTER);
	public static final RegistryObject<Item> SPATIAL_TELEPORTER_BLOCK = block(EriniumModBlocks.SPATIAL_TELEPORTER_BLOCK);
	public static final RegistryObject<Item> TOUR_TRADI = block(EriniumModBlocks.TOUR_TRADI);
	public static final RegistryObject<Item> EXTRACTOR_EMPTY = block(EriniumModBlocks.EXTRACTOR_EMPTY);
	public static final RegistryObject<Item> EXTRACTOR_BOTTLE_EMPTY = block(EriniumModBlocks.EXTRACTOR_BOTTLE_EMPTY);
	public static final RegistryObject<Item> EXTRACTOR_AMENINE_1 = block(EriniumModBlocks.EXTRACTOR_AMENINE_1);
	public static final RegistryObject<Item> EXTRACTOR_AMENINE_2 = block(EriniumModBlocks.EXTRACTOR_AMENINE_2);
	public static final RegistryObject<Item> EXTRACTOR_AMENINE_3 = block(EriniumModBlocks.EXTRACTOR_AMENINE_3);
	public static final RegistryObject<Item> EXTRACTOR_AMENINE_4 = block(EriniumModBlocks.EXTRACTOR_AMENINE_4);
	public static final RegistryObject<Item> EXTRACTOR_AMENINE_5 = block(EriniumModBlocks.EXTRACTOR_AMENINE_5);
	public static final RegistryObject<Item> FRAISAGE_NUMERIQUE = block(EriniumModBlocks.FRAISAGE_NUMERIQUE);
	public static final RegistryObject<Item> FONDERIE = block(EriniumModBlocks.FONDERIE);
	public static final RegistryObject<Item> EGG_FACTORY = block(EriniumModBlocks.EGG_FACTORY);
	public static final RegistryObject<Item> NETHER_STAR_GEN = block(EriniumModBlocks.NETHER_STAR_GEN);
	public static final RegistryObject<Item> BLOOD_ORB = REGISTRY.register("blood_orb", () -> new BloodOrbItem());
	public static final RegistryObject<Item> MAGIC_WAND_COBWEB = REGISTRY.register("magic_wand_cobweb", () -> new MagicWandCobwebItem());
	public static final RegistryObject<Item> ERINIUM_BUSH = block(EriniumModBlocks.ERINIUM_BUSH);
	public static final RegistryObject<Item> WARNING_LOGO = REGISTRY.register("warning_logo", () -> new WarningLogoItem());
	public static final RegistryObject<Item> ERINIUM_TAB_ANIMATION = REGISTRY.register("erinium_tab_animation", () -> new EriniumTabAnimationItem());
	public static final RegistryObject<Item> MAGICAL_WAND = REGISTRY.register("magical_wand", () -> new MagicalWandItem());
	public static final RegistryObject<Item> SETANUM_STAGE_0 = block(EriniumModBlocks.SETANUM_STAGE_0);
	public static final RegistryObject<Item> SETANUM_STAGE_1 = block(EriniumModBlocks.SETANUM_STAGE_1);
	public static final RegistryObject<Item> SETANUM_STAGE_2 = block(EriniumModBlocks.SETANUM_STAGE_2);
	public static final RegistryObject<Item> SETANUM_STAGE_3 = block(EriniumModBlocks.SETANUM_STAGE_3);
	public static final RegistryObject<Item> ALPHA_MARQUED = block(EriniumModBlocks.ALPHA_MARQUED);
	public static final RegistryObject<Item> BETA_MARQUED = block(EriniumModBlocks.BETA_MARQUED);
	public static final RegistryObject<Item> CHARLIE_MARQUED = block(EriniumModBlocks.CHARLIE_MARQUED);
	public static final RegistryObject<Item> DELTA_MARQUED = block(EriniumModBlocks.DELTA_MARQUED);
	public static final RegistryObject<Item> TREE_BOSS_PROJECTILE = REGISTRY.register("tree_boss_projectile", () -> new TreeBossProjectileItem());
	public static final RegistryObject<Item> JL_SKYZER_PAINTING = block(EriniumModBlocks.JL_SKYZER_PAINTING);
	public static final RegistryObject<Item> JL_SKYZER_PAINTING_2 = block(EriniumModBlocks.JL_SKYZER_PAINTING_2);
	public static final RegistryObject<Item> ERINIUM_BACKGROUND = block(EriniumModBlocks.ERINIUM_BACKGROUND);
	public static final RegistryObject<Item> ERINIUM_LOGO = block(EriniumModBlocks.ERINIUM_LOGO);
	public static final RegistryObject<Item> RAINBOW_SWORD = REGISTRY.register("rainbow_sword", () -> new RainbowSwordItem());
	public static final RegistryObject<Item> RAINBOW_PICKAXE = REGISTRY.register("rainbow_pickaxe", () -> new RainbowPickaxeItem());
	public static final RegistryObject<Item> RAINBOW_AXE = REGISTRY.register("rainbow_axe", () -> new RainbowAxeItem());
	public static final RegistryObject<Item> RAINBOW_SHOVEL = REGISTRY.register("rainbow_shovel", () -> new RainbowShovelItem());
	public static final RegistryObject<Item> ALMONIE_GEM = REGISTRY.register("almonie_gem", () -> new AlmonieGemItem());
	public static final RegistryObject<Item> ALMONIE_PAPER = REGISTRY.register("almonie_paper", () -> new AlmoniePaperItem());
	public static final RegistryObject<Item> ALMONIE_CARD = REGISTRY.register("almonie_card", () -> new AlmonieCardItem());
	public static final RegistryObject<Item> SPECTRIUM_BATTERY = block(EriniumModBlocks.SPECTRIUM_BATTERY);
	public static final RegistryObject<Item> ERINIUM_WORKBENCH_TIER_1 = block(EriniumModBlocks.ERINIUM_WORKBENCH_TIER_1);
	public static final RegistryObject<Item> TIER_1_CRAFTING_BENCH = REGISTRY.register("tier_1_crafting_bench", () -> new Tier1CraftingBenchItem());
	public static final RegistryObject<Item> ERINIUM_MATRIX_INGOT = REGISTRY.register("erinium_matrix_ingot", () -> new EriniumMatrixIngotItem());
	public static final RegistryObject<Item> ERINIUM_MATRIX_ARMOR_HELMET = REGISTRY.register("erinium_matrix_armor_helmet", () -> new EriniumMatrixArmorItem.Helmet());
	public static final RegistryObject<Item> ERINIUM_MATRIX_ARMOR_CHESTPLATE = REGISTRY.register("erinium_matrix_armor_chestplate", () -> new EriniumMatrixArmorItem.Chestplate());
	public static final RegistryObject<Item> ERINIUM_MATRIX_ARMOR_LEGGINGS = REGISTRY.register("erinium_matrix_armor_leggings", () -> new EriniumMatrixArmorItem.Leggings());
	public static final RegistryObject<Item> ERINIUM_MATRIX_ARMOR_BOOTS = REGISTRY.register("erinium_matrix_armor_boots", () -> new EriniumMatrixArmorItem.Boots());
	public static final RegistryObject<Item> ERINIUM_MATRIX_BLOCK = block(EriniumModBlocks.ERINIUM_MATRIX_BLOCK);
	public static final RegistryObject<Item> ERINIUM_MATRIX_SWORD = REGISTRY.register("erinium_matrix_sword", () -> new EriniumMatrixSwordItem());
	public static final RegistryObject<Item> ERINIUM_MATRIX_PICKAXE = REGISTRY.register("erinium_matrix_pickaxe", () -> new EriniumMatrixPickaxeItem());
	public static final RegistryObject<Item> ERINIUM_MATRIX_AXE = REGISTRY.register("erinium_matrix_axe", () -> new EriniumMatrixAxeItem());
	public static final RegistryObject<Item> HACKED_USB_KEY = REGISTRY.register("hacked_usb_key", () -> new HackedUsbKeyItem());
	public static final RegistryObject<Item> ICY_MUSHROOM = block(EriniumModBlocks.ICY_MUSHROOM);
	public static final RegistryObject<Item> LANTERN_PLANT = block(EriniumModBlocks.LANTERN_PLANT);
	public static final RegistryObject<Item> HOT_WATER_BUCKET = REGISTRY.register("hot_water_bucket", () -> new HotWaterItem());
	public static final RegistryObject<Item> RED_JUNGLE_DIRT = block(EriniumModBlocks.RED_JUNGLE_DIRT);
	public static final RegistryObject<Item> RED_JUNGLE_GRASS = block(EriniumModBlocks.RED_JUNGLE_GRASS);
	public static final RegistryObject<Item> ROCK_VOLCANO = block(EriniumModBlocks.ROCK_VOLCANO);
	public static final RegistryObject<Item> LASER_DRILL = REGISTRY.register("laser_drill", () -> new LaserDrillItem());
	public static final RegistryObject<Item> ASTRAL_MINER_FOOT = REGISTRY.register("astral_miner_foot", () -> new AstralMinerFootItem());
	public static final RegistryObject<Item> ASTRAL_MINER_LASER_MODULE = REGISTRY.register("astral_miner_laser_module", () -> new AstralMinerLaserModuleItem());
	public static final RegistryObject<Item> ASTRAL_MINER = block(EriniumModBlocks.ASTRAL_MINER);
	public static final RegistryObject<Item> COBBLE_VOID_STATION = block(EriniumModBlocks.COBBLE_VOID_STATION);
	public static final RegistryObject<Item> ENERGY_SELLER = block(EriniumModBlocks.ENERGY_SELLER);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
